[build]
  publish = "."

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
